from abc import ABC, abstractmethod
import os
import re
from typing import List, Dict
from huggingface_hub import repo_exists

MAX_OUTPUT_TOKENS = 512


class Model(ABC):

    def __init__(self, model_name_or_path: str):
        self.model_name_or_path = model_name_or_path

    @abstractmethod
    def generate(
        self,
        system_prompts: List[str],
        input_texts: List[str],
    ) -> List[List[str]]:
        """
        Input is a list of system prompts and a list of input texts.
        Each system prompt corresponds to a message in the input_texts list.
        The method should return a list of lists, where each inner list
        contains the generated responses for each message.
        The inner list is the amount of responses generated by the model.
        """
        pass

    def get_response_data(
        self,
        responses: List[List[str]],
    ) -> Dict[str, List[List[str]]]:
        """
        Extracts the response data from the generated responses.
        The method should return a dictionary with the following structure:
        {
            "output": List[List[str]] # all generated outputs
            "extracted_answers": List[List[str]] # extracted answers
        }
        """
        all_outputs = []
        all_extracted_answers = []

        # responses is a list of lists,
        # the inner list is num_generations responses for each input text
        # we call this a response_batch here, it has nothing do with the batch size
        for response_batch in responses:
            outputs = []
            extracted_answers = []
            for response in response_batch:
                outputs.append(response)
                extracted_answer = self.extract_answer(response)
                extracted_answers.append(extracted_answer)
            all_outputs.append(outputs)
            all_extracted_answers.append(extracted_answers)

        return {
            "output": all_outputs,
            "extracted_answers": all_extracted_answers,
        }

    def extract_answer(self, text: str) -> str | None:
        """
        Given a text, extract the answer from it.
        The answer can be one of "Answer1", "Answer2", or "Tie".
        If the answer is ambiguous (e.g. both "Answer1" and "Answer2" are present), return None.
        If no answer is found, return None.
        """
        # Try to match at the start of the text
        match_start = re.match(
            r"^\s*(Answer1|Answer2|Tie)\s*",
            text.strip().split("\n")[0],
            flags=re.IGNORECASE,
        )
        # Try to match at the end of the text
        match_end = re.match(
            r"\s*(Answer1|Answer2|Tie)\s*$",
            text.strip().split("\n")[-1],
            flags=re.IGNORECASE,
        )

        # when gpt-oss uses "thinking" in the answer the answer will be at the very end but prepended "assistantfinal"
        # e.g. "assistantfinalAnswer1"
        # we simply just look at the last word and see whether it matches
        match_thinking = re.search(
            r"(Answer1|Answer2|Tie)\s*$",
            text.strip().split("\n")[-1],
            flags=re.IGNORECASE,
        )

        # If both start and end match but are different, return None (ambiguous answer)
        if (
            match_start
            and match_end
            and match_start.group(1).lower() != match_end.group(1).lower()
        ):
            return None
        if match_start:
            return match_start.group(1).lower()
        if match_end:
            return match_end.group(1).lower()
        if match_thinking:
            return match_thinking.group(1).lower()
        # If neither matches, return None (no answer found)
        return None
    
class vLLMModel(Model):
    def __init__(self, model_name_or_path: str, config: dict, tasks: dict):
        from vllm import LLM, SamplingParams
        # from vllm.sampling_params import BeamSearchParams
        # from torch.cuda import device_count

        super().__init__(model_name_or_path)

        if config.get("model_zipped"):
            # unzip the model to TMPDIR if it is zipped
            import zipfile
            with zipfile.ZipFile(model_name_or_path, 'r') as zip_ref:
                tmpdir = os.environ.get("TMPDIR")
                if tmpdir is None:
                    raise ValueError("TMPDIR environment variable not set.")
                unzip_path = os.path.join(tmpdir, os.path.basename(model_name_or_path) + "_unzipped")
                zip_ref.extractall(unzip_path)
                model_name_or_path = unzip_path

        self.llm = LLM(
            model=model_name_or_path,
            tensor_parallel_size=tasks["vllm_parameters"].get("tensor_parallel_size", 2), # device_count()
            dtype=tasks["model_parameters"].get("dtype", "bfloat16"),
            max_model_len=tasks["model_parameters"].get("max_model_length", 512),
            tokenizer_mode="mistral",
            limit_mm_per_prompt={"image": 0}, # disable multimodal for this project
        )

        # Clean up sampling parameters by removing None values
        sampling_params = tasks.get("sampling_parameters", {})
        for key, item in list(sampling_params.items()):
            if item is None:
                del sampling_params[key]

        # Decide whether to use sampling or beam search
        self.has_sampling_param = any(
            k in sampling_params for k in ("temperature", "top_p", "min_p", "top_k")
        )

        # if self.has_sampling_param:
        # Use SamplingParams when any sampling parameter is set
        self.sampling_params = SamplingParams(
            # TODO: (also see in generate method) Decide whether we want to continue using our own sampling params
            # or just use the sampling params recommended by the model creators, which get loaded automatically if we don't set them here
            # temperature=sampling_params.get("temperature", 0.0),
            # top_p=sampling_params.get("top_p", 1.0),
            # min_p=sampling_params.get("min_p", 0.0),
            # top_k=sampling_params.get("top_k", -1),
            n=tasks["model_parameters"].get("num_generations", 3),
            max_tokens=tasks["model_parameters"].get(
                "max_output_tokens", MAX_OUTPUT_TOKENS
            ),
        )
        # else:
        #     self.beam_search_params = BeamSearchParams(
        #         beam_width=tasks["model_parameters"].get("num_generations", 3),
        #         max_tokens=tasks["model_parameters"].get(
        #             "max_output_tokens", MAX_OUTPUT_TOKENS
        #         ),
        #     )
    
    def format_inputs(
        self,
        input_texts: List[str],
        system_prompts: List[str],
    ) -> List[str]:
        formatted_inputs = [
            (sys_prompt + "\n" if sys_prompt else "") + input_text
            for input_text, sys_prompt in zip(input_texts, system_prompts)
        ]
        return formatted_inputs

    def generate(
        self,
        system_prompts: List[str],
        input_texts: List[str],
    ) -> List[List[str]]:
        inputs = self.format_inputs(input_texts, system_prompts)

        # if self.has_sampling_param:
        outputs = self.llm.generate(inputs, self.sampling_params)
        # outputs has this format: outputs[j].output.outputs[i].text
        outputs = [[output.text for output in generation.outputs] for generation in outputs]
        # else:
            # TODO: Decide whether we want to continue using beam search or just use the sampling params recommended by the model creators
            # beam_inputs = [{"prompt": text} for text in inputs]
            # outputs = self.llm.beam_search(beam_inputs, self.beam_search_params)
            # # outputs has this format: outputs[j].output.outputs[i].text
            # outputs = [[output.text for output in generation.outputs] for generation in outputs]

        return outputs


def get_model(model_name_or_path: str, config: dict, tasks: dict) -> Model:
    if repo_exists(
        model_name_or_path, repo_type="model", token=config.get("huggingface_hub_token")
    ):
        # Some models are restricted and require a token to access
        from huggingface_hub import login

        if not (token := config.get("huggingface_hub_token")):
            raise ValueError(
                "Hugging Face Hub token is required for Hugging Face models."
            )
        login(token)

        return vLLMModel(model_name_or_path, config, tasks)
    else:
        raise ValueError(f"Model {model_name_or_path} not supported.")
