from abc import ABC, abstractmethod
import re
from typing import List, Dict
from huggingface_hub import repo_exists

MAX_OUTPUT_TOKENS = 512


class Model(ABC):

    def __init__(self, model_name_or_path: str):
        self.model_name_or_path = model_name_or_path

    @abstractmethod
    def generate(
        self,
        system_prompts: List[str],
        input_texts: List[str],
    ) -> List[List[str]]:
        """
        Input is a list of system prompts and a list of input texts.
        Each system prompt corresponds to a message in the input_texts list.
        The method should return a list of lists, where each inner list
        contains the generated responses for each message.
        The inner list is the amount of responses generated by the model.
        """
        pass

    def get_response_data(
        self,
        responses: List[List[str]],
    ) -> Dict[str, List[List[str]]]:
        """
        Extracts the response data from the generated responses.
        The method should return a dictionary with the following structure:
        {
            "output": List[List[str]] # all generated outputs
            "extracted_answers": List[List[str]] # extracted answers
        }
        """
        all_outputs = []
        all_extracted_answers = []

        # responses is a list of lists,
        # the inner list is num_generations responses for each input text
        # we call this a response_batch here, it has nothing do with the batch size
        for response_batch in responses:
            outputs = []
            extracted_answers = []
            for response in response_batch:
                outputs.append(response)
                extracted_answer = self.extract_answer(response)
                extracted_answers.append(extracted_answer)
            all_outputs.append(outputs)
            all_extracted_answers.append(extracted_answers)

        return {
            "output": all_outputs,
            "extracted_answers": all_extracted_answers,
        }

    def extract_answer(self, text: str) -> str | None:
        """
        Given a text, extract the answer from it.
        The answer can be one of "Answer1", "Answer2", or "Tie".
        If the answer is ambiguous (e.g. both "Answer1" and "Answer2" are present), return None.
        If no answer is found, return None.
        """
        # Try to match at the start of the text
        match_start = re.match(
            r"^\s*(Answer1|Answer2|Tie)\s*",
            text.strip().split("\n")[0],
            flags=re.IGNORECASE,
        )
        # Try to match at the end of the text
        match_end = re.match(
            r"\s*(Answer1|Answer2|Tie)\s*$",
            text.strip().split("\n")[-1],
            flags=re.IGNORECASE,
        )

        # when gpt-oss uses "thinking" in the answer the answer will be at the very end but prepended "assistantfinal"
        # e.g. "assistantfinalAnswer1"
        # we simply just look at the last word and see whether it matches
        match_thinking = re.search(
            r"(Answer1|Answer2|Tie)\s*$",
            text.strip().split("\n")[-1],
            flags=re.IGNORECASE,
        )

        # If both start and end match but are different, return None (ambiguous answer)
        if (
            match_start
            and match_end
            and match_start.group(1).lower() != match_end.group(1).lower()
        ):
            return None
        if match_start:
            return match_start.group(1).lower()
        if match_end:
            return match_end.group(1).lower()
        if match_thinking:
            return match_thinking.group(1).lower()
        # If neither matches, return None (no answer found)
        return None
    
class vLLMModel(Model):
    def __init__(self, model_name_or_path: str, config: dict, tasks: dict):
        from vllm import LLM, SamplingParams

        super().__init__(model_name_or_path)
        self.llm = LLM(
            model=model_name_or_path,
            tensor_parallel_size=tasks["vllm_parameters"].get("tensor_parallel_size", 1),
            dtype=tasks["model_parameters"].get("dtype", "bfloat16"),
        )

        self.sampling_params = SamplingParams(
            temperature=tasks["sampling_parameters"].get("temperature", 0.0),
            top_p=tasks["sampling_parameters"].get("top_p", 1.0),
            min_p=tasks["sampling_parameters"].get("min_p", 0.0),
            top_k=tasks["sampling_parameters"].get("top_k", -1),
            n=tasks["model_parameters"].get("num_generations", 3),
            max_tokens=tasks["model_parameters"].get("max_output_tokens", MAX_OUTPUT_TOKENS)
        )
    
    def format_inputs(
        self,
        input_texts: List[str],
        system_prompts: List[str],
    ) -> List[str]:
        formatted_inputs = [
            (sys_prompt + "\n" if sys_prompt else "") + input_text
            for input_text, sys_prompt in zip(input_texts, system_prompts)
        ]
        return formatted_inputs

    def generate(
        self,
        system_prompts: List[str],
        input_texts: List[str],
    ) -> List[List[str]]:
        inputs = self.format_inputs(input_texts, system_prompts)

        outputs = self.llm.generate(inputs, self.sampling_params)
        # outputs has this format: outputs[j].output.outputs[i].text
        outputs = [[output.text for output in generation.outputs] for generation in outputs]

        return outputs


def get_model(model_name_or_path: str, config: dict, tasks: dict) -> Model:
    if repo_exists(
        model_name_or_path, repo_type="model", token=config.get("huggingface_hub_token")
    ):
        # Some models are restricted and require a token to access
        from huggingface_hub import login

        if not (token := config.get("huggingface_hub_token")):
            raise ValueError(
                "Hugging Face Hub token is required for Hugging Face models."
            )
        login(token)

        return vLLMModel(model_name_or_path, config, tasks)
    else:
        raise ValueError(f"Model {model_name_or_path} not supported.")
