from abc import ABC, abstractmethod
import re
from string import ascii_letters, digits
from typing import List, Dict
from openai import OpenAI
from google import genai
from google.genai.types import GenerateContentConfig
from tqdm import trange
from transformers import AutoModelForCausalLM, AutoTokenizer # type: ignore
import torch
from huggingface_hub import repo_exists

class Model(ABC):

    def __init__(self, model_name_or_path: str):
        self.model_name_or_path = model_name_or_path

    @abstractmethod
    def generate(
        self,
        system_prompts: List[str],
        input_texts: List[str],
        num_generations: int = 1,
        **kwargs,
    ) -> List[List[str]]:
        """
        Input is a list of system prompts and a list of input texts.
        Each system prompt corresponds to a message in the input_texts list.
        The method should return a list of lists, where each inner list 
        contains the generated responses for each message.
        The inner list is the amount of responses generated by the model.
        """
        pass

    def get_response_data(
        self,
        responses: List[List[str]],
    ) -> Dict[str, List[str]]:
        """
        Extracts the response data from the generated responses.
        The method should return a dictionary with the following structure:
        {
            "output": List[List[str]] # all generated outputs
            "extracted_answers": List[List[str]] # extracted answers
        }
        """
        all_outputs = []
        all_extracted_answers = []

        # responses is a list of lists,
        # the inner list is num_generations responses for each input text 
        # we call this a response_batch here, it has nothing do with the batch size
        for response_batch in responses:
            outputs = []
            extracted_answers = []
            for response in response_batch:
                outputs.append(response)
                extracted_answer = self.extract_answer(response)
                extracted_answers.append(extracted_answer)
            all_outputs.append(outputs)
            all_extracted_answers.append(extracted_answers)

        return {
            "output": all_outputs,
            "extracted_answers": all_extracted_answers,
        }

    def apply_chat_template(
        self,
        input_text: str,
        system_prompt: str = "",
    ) -> List[Dict[str, str]]:
        """
        OpenAI uses this template directly.
        HuggingFace models have a method .apply_chat_template() themselves, 
        that takes the output of this method and applies it to the model.
        Gemini models need to override this method to apply the chat template, 
        since they can not be passed a role-based chat template like OpenAI or HuggingFace. 
        """
        input_texts = []
        if system_prompt:
            input_texts.append({"role": "system", "content": system_prompt})
        input_texts.append({"role": "user", "content": input_text})
        return input_texts
    
    def extract_answer(self, text: str) -> str | None:
        """
        Given a text, extract the answer from it.
        The answer can be one of "Answer1", "Answer2", or "Tie".
        If the answer is ambiguous (e.g. both "Answer1" and "Answer2" are present), return None.
        If no answer is found, return None.
        """
        # Try to match at the start of the text
        match_start = re.match(r'^\s*(Answer1|Answer2|Tie)\s*$', text.strip().split('\n')[0], flags=re.IGNORECASE)
        # Try to match at the end of the text
        match_end = re.match(r'^\s*(Answer1|Answer2|Tie)\s*$', text.strip().split('\n')[-1], flags=re.IGNORECASE)
        
        # If both start and end match but are different, return None (ambiguous answer)
        if match_start and match_end and match_start.group(1).lower() != match_end.group(1).lower():
            return None
        if match_start:
            return match_start.group(1).lower()
        if match_end:
            return match_end.group(1).lower()
        # If neither matches, return None (no answer found)
        return None
    
class HuggingfaceModel(Model):
    def __init__(self, model_name_or_path: str):
        super().__init__(model_name_or_path)
        self.model = AutoModelForCausalLM.from_pretrained(
            model_name_or_path,
            torch_dtype=torch.float16,
            device_map="auto",
            max_memory={0: "92GB", 1: "92GB"}
        )
        self.tokenizer = AutoTokenizer.from_pretrained(model_name_or_path)
        self.tokenizer.pad_token = self.tokenizer.eos_token
        self.tokenizer.padding_side = "left"
        self.model.generation_config.pad_token_id = self.tokenizer.pad_token_id

        # Newer models are optimized for chat-based interactions and have a chat template
        self.has_chat_template = hasattr(self.tokenizer, "chat_template") and self.tokenizer.chat_template is not None

        self.model.eval()

    def generate(
        self,
        system_prompts: List[str],
        input_texts: List[str],
        num_generations: int = 1,
        **kwargs,
    ) -> List[List[str]]:
        """
        Batched inference for HuggingfaceModel.
        """
        # Not all models support batched inference and max_output_tokens, so it is not passed as an argument.
        batch_size = kwargs.get("batch_size", 8)
        max_output_tokens = kwargs.get("max_output_tokens", 512)

        print(f"Processing {len(input_texts)} examples")
        print(f"Batch size: {batch_size}")
        print(f"Number of generations: {num_generations}")
        print(f"Max output tokens: {max_output_tokens}")

        all_outputs = []

        for i in trange(0, len(input_texts), batch_size, desc="Processing batches", unit="batch"):
            batch_system_prompts = system_prompts[i:i+batch_size]
            batch_input_texts = input_texts[i:i+batch_size]

            if self.has_chat_template:
                messages_batch = [
                    self.apply_chat_template(input_text, sys_prompt)
                    for input_text, sys_prompt in zip(batch_input_texts, batch_system_prompts)
                ]
                formatted_inputs = [
                    self.tokenizer.apply_chat_template(
                        msgs,
                        return_tensors="pt",
                        tokenize=False,
                        add_generation_prompt=True,
                        max_length=self.tokenizer.model_max_length,
                    )
                    for msgs in messages_batch
                ]
            else:
                # If no chat template is available, just concatenate the system prompt and input text
                formatted_inputs = [
                    (sys_prompt + "\n" if sys_prompt else "") + input_text
                    for input_text, sys_prompt in zip(batch_input_texts, batch_system_prompts)
                ]

            inputs = self.tokenizer(
                formatted_inputs,
                return_tensors="pt",
                padding=True,
                truncation=True,
                max_length=self.tokenizer.model_max_length,
            )
            inputs = inputs.to(self.model.device)
            input_length = inputs['input_ids'].shape[1]

            # remove items from kwargs to avoid passing it to the model
            explicit_keys = ["do_sample", "top_p", "top_k", "temperature", "max_output_tokens"]
            explicit_kwargs = {k: kwargs.pop(k, None) for k in explicit_keys}

            with torch.no_grad():
                output = self.model.generate(
                    **inputs,
                    max_new_tokens=max_output_tokens,
                    num_beams=num_generations,
                    num_return_sequences=num_generations,
                    do_sample=explicit_kwargs["do_sample"] if explicit_kwargs["do_sample"] is not None else False,
                    top_p=explicit_kwargs["top_p"],
                    top_k=explicit_kwargs["top_k"],
                    temperature=explicit_kwargs["temperature"],
                    return_dict_in_generate=True,
                    **kwargs,
                )

            sequences = output.sequences
            # Remove the input part from the generated sequences
            generated_sequences = sequences[:, input_length:]
            decoded_sequences = self.tokenizer.batch_decode(
                generated_sequences, skip_special_tokens=True
            )
            responses = [seq.strip() for seq in decoded_sequences]
            all_outputs.append(responses)

        return all_outputs
    
class OpenAIModel(Model):
    def __init__(self, model_name_or_path: str, api_key: str):
        super().__init__(model_name_or_path)
        self.openai_client = OpenAI(api_key=api_key)

    def generate(
        self,
        system_prompts: List[str],
        input_texts: List[str],
        num_generations: int = 1,
        **kwargs,
    ) -> List[List[str]]:
        
        responses = []
        for input_text, system_prompt in zip(input_texts, system_prompts):
            message = self.apply_chat_template(input_text, system_prompt)
            response_batch = []
            for _ in range(num_generations):
                response = self.openai_client.responses.create(
                    model=self.model_name_or_path,
                    input=message, # type: ignore
                    max_output_tokens=kwargs.get("max_output_tokens", 512), # type: ignore
                )
                response_batch.append(response.output_text)
            responses.append(response_batch)

        return responses
    
class GeminiModel(Model):
    def __init__(self, model_name_or_path: str, api_key: str):
        super().__init__(model_name_or_path)
        self.client = genai.Client(api_key=api_key)

    def generate(
        self,
        system_prompts: List[str],
        input_texts: List[str],
        num_generations: int = 1,
        **kwargs,
    ) -> List[List[str]]:
        responses = []
        for input_text, system_prompt in zip(input_texts, system_prompts):
            if system_prompt:
                config = GenerateContentConfig(
                    max_output_tokens=kwargs.get("max_output_tokens", 512),
                    system_instruction=system_prompt,
                )
            else:
                config = GenerateContentConfig(
                    max_output_tokens=kwargs.get("max_output_tokens", 512),
                )

            response_batch = []
            for _ in range(num_generations):
                response = self.client.models.generate_content(
                    model=self.model_name_or_path,
                    contents=input_text,
                    config=config
                )
                response_batch.append(response.text)
            responses.append(response_batch)

        return responses

class RandomAnswer(Model):
    def __init__(self):
        """
        This model is for debugging purposes only.
        It randomly chooses between "Answer1", "Answer2", and "Tie" as the output.
        This is useful to test the pipeline without needing the hardware to run a big LLM
        or using API credits.
        """
        super().__init__("random_choice_model")

    def generate(
        self,
        system_prompts: List[str],
        input_texts: List[str],
        num_generations: int = 1,
        **kwargs,
    ) -> List[List[str]]:
        from random import choice

        responses = []
        for input_text, system_prompt in zip(input_texts, system_prompts):
            response_batch = []
            for _ in range(num_generations):
                response = choice(ascii_letters + digits + "Answer1"+ "Answer2" + "Tie")
                response_batch.append(response)
            responses.append(response_batch)
        return responses

def get_model(model_name_or_path: str, config: dict, **kwargs) -> Model:
    if repo_exists(model_name_or_path, repo_type="model"):
        # Some models are restricted and require a token to access
        from huggingface_hub import login
        if not (token := config.get("huggingface_hub_token")):
            raise ValueError("Hugging Face Hub token is required for Hugging Face models.")
        login(token)
        
        return HuggingfaceModel(model_name_or_path, **kwargs)
    
    elif "gpt" in model_name_or_path:
        if not (api_key := config.get("openai_key")):
            raise ValueError("API key is required for OpenAI models.")
        return OpenAIModel(model_name_or_path, api_key)
    
    elif "gemini" in model_name_or_path:
        if not (api_key := config.get("gemini_key")):
            raise ValueError("API key is required for Gemini models.")
        return GeminiModel(model_name_or_path, api_key)
    elif model_name_or_path == "RandomAnswer":
        return RandomAnswer()
    else:
        raise ValueError(f"Model {model_name_or_path} not supported.")
